lib/chat_web/router.ex
defmodule ChatWeb.Router do
  use ChatWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ChatWeb do
    pipe_through :browser

    get "/", UserController, :index
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
    resources "/users", UserController
  end

  # Other scopes may use custom stacks.
  # scope "/api", ChatWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ChatWeb.Telemetry
    end
  end
end

lib/chat_web/views/layout_view.ex
defmodule ChatWeb.LayoutView do
  use ChatWeb, :view
end

lib/chat_web/templates/layout/_navbar.html.eex
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
<%= link "All Users", to: user_path(@conn, :index), class: "nav-link" %>    
<ul class="navbar-nav">
        <li class="nav-item ">
        <% if logged_in?(@conn) do %>
        <span class="badge badge-dark mr-2"><%= current_user(@conn).username %></span>
        <%= link "Logout", to: session_path(@conn, :delete), method: :delete, class: "btn btn-secondary" %>
        
        </li>
        <% else %>
        <li class="nav-item">
            <%= link "Login", to: session_path(@conn, :new) %>
        </li>
        <li class="nav-item">
            <%= link "Register", to: user_path(@conn, :new) %>
        </li>
        
    </ul>
    <% end %>
</nav>

lib/chat_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Chat · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>"/>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script defer type="text/javascript" src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <style>body {font-family: Arial, Helvetica, sans-serif;}
    
    </style>
  
  
  </head>
  <body>
    <div class="container">
    <%= render "_navbar.html", conn: @conn %>
    </div>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>